name: ArgoCD Sync

on:
  push:
    branches:
      - testing
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      ARGOCD_PASSWORD:
        required: true
      ARGOCD_SERVER:
        required: true
      ARGOCD_USER:
        required: true

permissions:
  id-token: write
  contents: write

env:
  ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}

jobs:
  argocd-sync:
    name: Syncing ${{ inputs.app_name }} in ArgoCD
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Logging into ArgoCD
        uses: clowdhaus/argo-cd-action@main
        env:
          ARGOCD_SERVER: ${{ env.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ vars.ARGOCD_USER }}
          ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
        with:
          command: login
          options: --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD

      - name: ArgoCD Sync ${{ inputs.app_name }}
        uses: clowdhaus/argo-cd-action/@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARGOCD_SERVER: ${{ env.ARGOCD_SERVER }}
        with:
          command: app sync
          options: ${{ inputs.app_name }}
