name: Sync Application using ArgoCD

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'The name of the application to deploy'
        required: true
        type: string

jobs:
  argocd-sync:
    name: Syncing ${{ inputs.app_name }} in ArgoCD
    uses: truemark/github-workflows/.github/workflows/argocd-sync.yml@argocd-demo
