name: ArgoCD Sync

on:
  push:
    branches:
      - testing
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      app_id:
        required: true
      private_key:
        required: true

permissions:
  id-token: write
  contents: write

env:
  ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}

jobs:
  argocd-sync:
    name: Syncing ${{ inputs.app_name }} in ArgoCD
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Generate token
        id: app-token
        uses: getsentry/action-github-app-token@v3
        with:
          app_id: ${{ secrets.app_id }}
          private_key: ${{ secrets.private_key }}

      - name: Logging into ArgoCD
        uses: clowdhaus/argo-cd-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARGOCD_SERVER: ${{ env.ARGOCD_SERVER }}
        with:
          command: login
          options: ${{ env.ARGOCD_SERVER }} --auth-token ${{ steps.app-token.outputs.token }}

      - name: ArgoCD Sync ${{ inputs.app_name }}
        uses: clowdhaus/argo-cd-action/@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARGOCD_SERVER: ${{ env.ARGOCD_SERVER }}
        with:
          command: app sync
          options: ${{ inputs.app_name }}
