name: ArgoCD Deployment

on:
  workflow_call:
    inputs:
      helm_chart_path:
        description: "Path to the Helm chart"
        required: true
        type: string
      github_user:
        description: "GitHub user"
        required: true
        type: string
      github_email:
        description: "GitHub email"
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tag

      - name: Set New Docker Tag
        run: echo "IMAGE_TAG=$(cat image-tag.txt)" >> $GITHUB_ENV

      - name: Update Tag in values.yaml
        run: |
          sed -i "s/^  tag: .*/  tag: ${IMAGE_TAG}/" ${{ inputs.helm_chart_path }}/values.yaml

      - name: Update Tag in Chart.yaml
        run: |
          sed -i "s/^appVersion: .*/appVersion: \"${IMAGE_TAG}\"/" ${{ inputs.helm_chart_path }}/Chart.yaml

      - name: Push Updates to values.yaml
        run: |
          git config --global user.name '${{ inputs.github_user }}'
          git config --global user.email '${{ inputs.github_email }}'
          git add ${{ inputs.helm_chart_path }}/*
          git commit -m "Update Docker Image. [skip ci]"
          git push
