name: ArgoCD Sync

on:
  push:
    branches:
      - testing
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      environment:
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  argocd-sync:
    name: Syncing ${{ inputs.app_name }} in ArgoCD
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: ArgoCD Sync ${{ inputs.app_name }}
        uses: clowdhaus/argo-cd-action/@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: app sync
          options: ${{ inputs.app_name }} --server 'https://argocd.stage.truemark.io'
