on:
  workflow_call:
    secrets:
      docker-hub-username:
        required: true
      docker-hub-password:
        required: true
    inputs:
      image_name:
        description: "Name of the image"
        required: true
        type: string
      version:
        description: "Version of the project"
        required: true
        type: string
      role-to-assume-devops:
        description: "Role to assume"
        required: true
        type: string
      region:
        description: "AWS Region"
        required: true
        type: string
      docker-hub-registry:
        description: "Docker Hub Registry"
        required: true
        type: string
      ecr-registry:
        description: "ECR Registry"
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-to-assume-devops }}
          aws-region: ${{ inputs.region }}

      - name: Login to ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.docker-hub-registry }}
          username: ${{ secrets.docker-hub-username }}
          password: ${{ secrets.docker-hub-password }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker
        env:
          REGISTRY: ${{ inputs.ecr-registry }}
        run: |
          docker buildx build \
            --push \
            --platform linux/amd64 \
            -f Dockerfile \
            -t ${{ env.REGISTRY }}/${{ inputs.image_name }}:${{ inputs.version }} \
            .

      - name: Create Version Artifact
        run: |
          echo ${{ inputs.version }} > image-tag.txt

      - name: Upload Docker Image Tag
        uses: actions/upload-artifact@v4
        with:
          name: image-tag
          path: image-tag.txt
