name: Maintenance Mode
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment of Application"
        required: true
        type: string
      namespace:
        description: "Namespace of Application"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  maintenance:
    runs-on: self-hosted
    steps:
      - name: Set ENV Variables
        id: set-env
        run: |
          ENVIRONMENT=$(echo "${{ inputs.environment }}" | tr '[:upper:]' '[:lower:]')
          NAMESPACE=$(echo "${{ inputs.namespace }}" | tr '[:upper:]' '[:lower:]')
          
          if [[ "$ENVIRONMENT" == "prod" ]]; then
            echo "ROLE=${{ vars.AWS_ASSUME_ROLE_PROD }}" >> $GITHUB_ENV
            echo 'MAINT_PAGE=oc-downpage.ptm-prod.svc.cluster.local' >> $GITHUB_ENV
          else
            echo "ROLE=${{ vars.AWS_ASSUME_ROLE_NON_PROD }}" >> $GITHUB_ENV
            if [[ "$NAMESPACE" == *"stage"* ]]; then
              echo 'MAINT_PAGE=oc-downpage.ptm-stage.svc.cluster.local' >> $GITHUB_ENV
            else
              echo 'MAINT_PAGE=oc-downpage.ptm-qa.svc.cluster.local' >> $GITHUB_ENV
            fi
          fi

      - name: Configure AWS Credentials
        id: configure-aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Cluster Access
        id: cluster-access
        run: |
          aws eks update-kubeconfig --name services --kubeconfig ./kubeconfig
          echo 'KUBECONFIG<<EOF' >> $GITHUB_ENV
          echo $(cat ./kubeconfig | base64) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}

      - name: Get Maintenance Mode Status
        id: check-maintenance
        uses: truemark/github-kubectl@main
        env:
          KUBECONFIG: "${{ env.KUBECONFIG }}"
        with:
          args: get deployment pingpong--web -n ${{ inputs.namespace }} -o jsonpath='{.metadata.labels.maintenance-mode}'

      - name: Set Maintenance Mode Variable
        run: |
          MAINT_MODE=$(cat ./output.txt | xargs)
          echo "MAINT_MODE=${MAINT_MODE}" >> $GITHUB_ENV

      - name: Get Pod Counts
        id: get-pod-counts
        uses: truemark/github-kubectl@main
        env:
          KUBECONFIG: "${{ env.KUBECONFIG }}"
        with:
          args: get deployment pingpong--web -n ${{ inputs.namespace }} -o jsonpath='{.metadata.labels.pod-count}'

      - name: Set Pod Count Variable
        run: echo "PODS=$(cat output.txt | xargs)" >> $GITHUB_ENV

      - name: Update Pod Count Label
        if: ${{ env.MAINT_MODE == 'false' }}
        uses: truemark/github-kubectl@main
        env:
          KUBECONFIG: "${{ env.KUBECONFIG }}"
        with:
          args: >
            patch deployment pingpong--web -n ${{ inputs.namespace }} --type=json --patch="[{\"op\": \"replace\", \"path\": \"/metadata/labels/pod-count\", \"value\": \"${{ env.PODS }}\"}]"

      - name: Update Maintenance Mode Label
        if: ${{ env.MAINT_MODE == 'false' }}
        uses: truemark/github-kubectl@main
        env:
          KUBECONFIG: "${{ env.KUBECONFIG }}"
        with:
          args: >
            patch deployment pingpong--web -n ${{ inputs.namespace }} --type=json --patch="[{\"op\": \"replace\", \"path\": \"/metadata/labels/maintenance-mode\", \"value\": \"true\"}]"

      - name: Scale Deployment Down
        if: ${{ env.MAINT_MODE == 'false' }}
        uses: truemark/github-kubectl@main
        env:
          KUBECONFIG: "${{ env.KUBECONFIG }}"
        with:
          args: scale deployment pingpong--web -n ${{ inputs.namespace }} --replicas=0

      - name: Enable Maintenance Mode
        if: ${{ env.MAINT_MODE == 'false' }}
        uses: truemark/github-kubectl@main
        env:
          KUBECONFIG: "${{ env.KUBECONFIG }}"
        with:
          args: >
            patch virtualservice pingpong-default-route -n ${{ inputs.namespace }} --type=json --patch="[
                {\"op\": \"replace\", \"path\": \"/spec/http/0/route/0/destination/host\", \"value\": \"${{ env.MAINT_PAGE }}\"},
                {\"op\": \"replace\", \"path\": \"/spec/http/0/route/0/destination/port/number\", \"value\": 5000}
              ]"

      - name: Disable Maintenance Mode
        if: ${{ env.MAINT_MODE == 'true' }}
        uses: truemark/github-kubectl@main
        env:
          KUBECONFIG: "${{ env.KUBECONFIG }}"
        with:
          args: >
            patch virtualservice pingpong-default-route -n ${{ inputs.namespace }} --type=json --patch="[
                {\"op\": \"replace\", \"path\": \"/spec/http/0/route/0/destination/host\", \"value\": \"pingpong--web\"},
                {\"op\": \"replace\", \"path\": \"/spec/http/0/route/0/destination/port/number\", \"value\": 9000}
            ]"

      - name: Updating Deployment Labels
        if: ${{ env.MAINT_MODE == 'true' }}
        uses: truemark/github-kubectl@main
        env:
          KUBECONFIG: "${{ env.KUBECONFIG }}"
        with:
          args: >
            patch deployment pingpong--web -n ${{ inputs.namespace }} --type=json --patch="[
                {\"op\": \"replace\", \"path\": \"/metadata/labels/maintenance-mode\", \"value\": \"false\"}
            ]"

      - name: Scale Deployment Back Up
        if: ${{ env.MAINT_MODE == 'true' }}
        uses: truemark/github-kubectl@main
        env:
          KUBECONFIG: "${{ env.KUBECONFIG }}"
        with:
          args: scale deployment pingpong--web -n ${{ inputs.namespace }} --replicas=${{ env.PODS }}



